golightstream/api.stream-studio-kit

package.json
src/helpers/compositor.tsx

Remove console log for css printed in console

---

package.json
src/compositor/html/html-layouts.tsx
src/compositor/layouts.ts
src/core/index.ts
src/core/layouts/index.ts
src/helpers/compositor.tsx

Various improvements to the responsiveness of the editor

Update layout behavior

---

src/core/commands.ts
src/core/data.ts
src/core/index.ts
src/core/requests.ts
src/core/transforms/Banner.tsx
src/core/types.ts
src/helpers/compositor.tsx
src/helpers/sceneless-project.ts

Support 1080p renderer

---

examples/studio-kit-demo/src/host/host.tsx
examples/studio-kit-demo/src/shared/control-panel.tsx
examples/studio-kit-demo/src/shared/participant.tsx
package-lock.json
src/core/events.ts
src/core/sources/WebRTC.ts
src/core/transforms/WebRTC.tsx
src/core/types.ts
src/core/webrtc/room-context.ts
src/core/webrtc/simple-room.ts
src/helpers/compositor.tsx
src/helpers/permission.ts
src/logic.ts

Feature: Mirroring support added in studio-kit

---

package-lock.json
package.json
src/core/transforms/Image2.tsx
src/core/transforms/Logo.tsx
src/core/transforms/Overlay.tsx
src/core/transforms/Video2.tsx
src/core/transforms/components/Iframe.tsx
src/core/transforms/components/Image.tsx
src/helpers/sceneless-project.ts

- fix multiple batch calls
- fix overlay layer updating multiple times
- improve fade transitions
- change the main layouts from free to 'layerd' to support proper zIndex
[sc-18861]
[sc-18860]

feat: improve studio performance

---

.github/workflows/deploy-renderer.yml
src/core/commands.ts
src/core/context.ts
src/core/index.ts
src/core/requests.ts

- Sets the version for project composition on create
- Updates the project composition when the broadcast is starting if needed
- Allows "advanced" override

chore: set sdk version for composition

---

.github/workflows/deploy-renderer.yml
package-lock.json
package.json
src/core/index.ts

Changed methods
Background :
> Previously
> 
> > setBackgroundImage('https://example.com/1.png')
> > setBackgroundVideo('https://example.com/1.mp4')
> 
> Now
> 
> > setBackgroundImage('id', { 'src' : 'https://example.com/1.png'})
> > setBackgroundVideo('id', { 'src' : 'https://example.com/1.mp4'})
Overlay:
> Previously
> 
>>  addImageOverlay(overlayId, 'https://example.com/1.png' )
>>  addVideoOverlay(overlayId, 'https://example.com/1.mp4' )
> 
> Now
> 
>>  addImageOverlay(overlayId, { src: 'https://example.com/1.png' })
>>  addVideoOverlay(overlayId, { src: 'https://example.com/1.mp4' })

chore: update the tags on pipeline to v2

---

package-lock.json
package.json
src/core/index.ts
src/core/webrtc/simple-room.ts

bumped version to 2.0.4
[sc-19063]
[sc-19064]

chore: added empty checks for places which throughts expection into joby

---

examples/studio-kit-demo/package.json
examples/studio-kit-demo/src/host/components/tile.tsx
examples/studio-kit-demo/src/host/data.ts
examples/studio-kit-demo/src/host/host.tsx
examples/studio-kit-demo/src/shared/chat.module.css

chore: update studio-kit demo examples

---

examples/studio-kit-demo/src/host/host.tsx
package-lock.json
package.json
src/core/commands.ts
src/core/sources/Game.ts
src/core/sources/RTMP.ts
src/core/transforms/GameSource.tsx
src/helpers/sceneless-project.ts
src/logic.ts

chore: add "console-integration" type

---

.github/workflows/deploy-renderer-without-publish.yml
.github/workflows/deploy-renderer.yml
build/hosted-renderer/directory-to-kv.js

It does not need a version bump.

fix: building renderer process

---

package-lock.json
package.json
src/core/commands.ts

https://xsolla.atlassian.net/browse/LSTREAM-290

chore: add triggerMetadata to startBroadcast

---

examples/studio-kit-demo/src/host/host.tsx
package.json
src/helpers/sceneless-project.ts

The dynamicSource type is changed from **'console-integration'** to **'integration'** in api.stream
https://xsolla.atlassian.net/browse/LSTREAM-69

chore: change console-integration to "integration"

---

package.json
src/helpers/engine-socket.ts

https://xsolla.atlassian.net/browse/LSTREAM-359

chore: update engine socketURL

---

package.json
src/core/sources/Game.ts
src/core/sources/WebRTC.ts

This pr fix game source preview support
https://xsolla.atlassian.net/browse/LSTREAM-361

fix: fix gamesource preview

---

examples/studio-kit-demo/src/host/host.tsx
package-lock.json
package.json
src/core/transforms/Overlay.tsx
src/helpers/database.ts
src/helpers/sceneless-project.ts

This pull request adds alert support to the studio-kit. The alerts have a fixed size, but they can scale to match changes in the feed resolution.
**TODO:** 
- Adds support for preview flag (This needs changes on rainmaker)
- Explore drag and drop feature
[LSTREAM-400](https://xsolla.atlassian.net/browse/LSTREAM-400)
[LSTREAM-400]: https://xsolla.atlassian.net/browse/LSTREAM-400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Adds support for alerts

---

package.json
src/core/layouts/index.ts
src/core/transforms/Alert.tsx
src/core/transforms/Overlay.tsx
src/core/transforms/index.ts
src/core/types.ts
src/helpers/compositor.tsx
src/helpers/database.ts
src/helpers/sceneless-project.ts

This PR advances the canvas positioning by allowing users to place alerts in specific hotspots displayed on the canvas
[LSTREAM-437](https://xsolla.atlassian.net/browse/LSTREAM-437)
[LSTREAM-437]: https://xsolla.atlassian.net/browse/LSTREAM-437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Adding Drag & Drop utility to alerts

---

package.json
src/core/commands.ts
src/core/transforms/GameSource.tsx
src/core/transforms/RTMPSource.tsx

This PR adds a function to retrieve the broadcast status, which is necessary for determining the broadcast duration.
Additionally, it removes the name banner form gamesource and rtmp source

chore: add function to get broadcast status

---

package-lock.json
package.json
src/core/transforms/GameSource.tsx
src/helpers/compositor.tsx

Also cleans up game source offline state. There are no designs, but I wanted it to look better for Twitchcon

Add source type to compositor item HTML

---

package.json
src/helpers/sceneless-project.ts

Participant methods should work for gamesource to control the audio.
https://xsolla.atlassian.net/browse/LSTREAM-731

chore: methods for participant should be able to work for gamesource

---

package-lock.json
package.json
src/helpers/database.ts
src/helpers/sceneless-project.ts

Alerts should be above the overlays in the order
https://xsolla.atlassian.net/browse/LSTREAM-740

chore: alerts should be above the overlays in the order

---

package-lock.json
package.json
src/core/transforms/GameSource.tsx

Ensure HTML play request promise handles exceptions properly.
https://xsolla.atlassian.net/browse/LSTREAM-784

fix: Handle exceptions for HTML play request promise

---

package-lock.json
package.json
src/core/index.ts

Added a guard to prevent firing trigger events when the project does not exist.
Removed unnecessary and unwanted code.

fix: sentry cleanup (Add Guard for Trigger Events and Code Cleanup)

---

.github/workflows/deploy-renderer-without-publish.yml
package.json
src/core/requests.ts

Filter only sceneless projects to avoid conflicts with scene-based projects created by XPN integration.
https://xsolla.atlassian.net/browse/LSTREAM-1130

chore: bump version to 3.0.49 and update project filtering logic in requests.ts
