- package.json
- src/core/types.ts
- src/core/webrtc/simple-room.ts
Surfaces the join time and the role of each participant in the room.
Using this as part of chat to identify a "primary" host, using a combination of the earliest `joinedAt` where `role=ROLE_HOST`
> feat: expose join time of participant and their role

- .github/workflows/deploy-renderer.yml
- .gitignore
- build/hosted-renderer/README.md
- build/hosted-renderer/directory-to-kv.js
- build/hosted-renderer/package-lock.json
- build/hosted-renderer/package.json
- build/hosted-renderer/src/index.ts
- build/hosted-renderer/tsconfig.json
- build/hosted-renderer/wrangler.toml
- build/license-header.json
- package.json
Uploads each release of the renderer to a CF worker so we can access each release of the SDK (the current method just stores the latest)
- Every commit to `main` will be stored as `latest` as it is today.
- Every tagged release will publish a version of the renderer.
> chore: upload renderer to a Cloudflare worker

- examples/studio-kit-demo/src/index.css
- src/core/transforms/WebRTC.tsx
- src/helpers/compositor.tsx
- src/helpers/sceneless-project.ts
This implements fixes for [15308](https://app.shortcut.com/lightstream/story/15308/check-styling-of-banners) to correctly size banners.
This also implements `getActiveBanner()` for [15468](https://app.shortcut.com/lightstream/story/15468/currently-active-text-banner-isn-t-displayed-as-active) to allow us to select the active banner correctly from studio2 and fixes a bug when deleting the active banner.
Screenshots of banners:
> fix: use correct banner sizes

- src/compositor/html/html-transforms.ts
- src/core/transforms/Banner.tsx
- src/helpers/sceneless-project.ts
A banner will be animated out once it no longer has a source. This enables us fluid and responsive animations between banners while relying on a single node.
> Improve banner responsiveness

- src/core/layouts/index.ts
A subpixel rendering issue in Chromium causes lower z-index layers to show from behind a layer in front of it even if they occupy the same bounding rectangle. 
This update forces each node in a Layered layout to extend 1px beyond the bounds of node behind it. This ensures the background isn't visible around full-screen content (e.g. screenshare presentation), and a full-screen content isn't visible around around a foreground video.
> Outset layered children by 1px

- package-lock.json
- package.json
The previous changes on studio-kit made renderer look up resources on `/$npm_package_version` path instead of `/v$npm_packge_version` path
> fix: remove prefix v from renderer build command

- package.json
- src/helpers/compositor.tsx
Recently this line was "fixed" by adding a semicolon, which enabled a legacy font-size control.
All banners have individual size control that are being over-written by this static font size.
> Remove font-size from banner containers

- package.json
- src/core/transforms/Image2.tsx
- src/core/transforms/Logo.tsx
- src/core/transforms/Overlay.tsx
- src/core/transforms/Video2.tsx
This element's parent has a `width` and `height` of `100%`, and the child (e.g. custom overlays) can potentially be the same. So, this needs to be the same as the parent for the child to be sized correctly.
> fix: fix full-size custom overlays

- src/core/commands.ts
- src/core/data.ts
This contains a fix for an issue caused by my last PR: https://github.com/golightstream/api.stream-studio-kit/pull/14
Spotted this while testing - since Joby Studio doesn't use the studio-kit method to start a broadcast, the sdk version is never updated. this means:
- Projects created before this release will forever be on "latest"
- Projects created after that release will forever render at that specific version.
We currently have a call to update the project on load, so I added some extra logic to update the SDK version (limited to hosts/cohosts). I've tested this with the demo app briefly.
> fix: update renderer version

- package-lock.json
- package.json
- renderer/renderer-main.ts
- src/core/sources/WebRTC.ts
- src/core/transforms/WebRTC.tsx
- src/helpers/database.ts
This has led to issues where the track's state was not being accurately reflected on showcase, causing confusion and errors.
[sc-19026]
> fix: mediaStreamTrack was not being updated when a track was enabled or disabled

- .github/workflows/deploy-renderer-without-publish.yml
- .github/workflows/deploy-renderer.yml
- build/hosted-renderer/directory-to-kv.js
- build/hosted-renderer/package-lock.json
- package.json
Currently, during the building of the renderer in studio-kit, the build process for the latest-v2 renderer uploads the files to Cloud flare KV, suffixed with "latest-v2". However, the Vite build generates the file with a reference to ${version} (ex 2.1.4). 
This creates a problem if the git build process for renderer-${version} fails. The index file for the latest-v2 renderer ends up referencing files that do not exist on Cloudflare KV.    
The build file for latest-v2 should have references in index.html updated to "latest-v2".
https://xsolla.atlassian.net/browse/LSTREAM-252
> chore: dynamic renderer version

- package.json
- src/core/layouts/index.ts
- src/core/transforms/Alert.tsx
- src/helpers/compositor.tsx
- src/helpers/sceneless-project.ts
This PR adds GameSource to the list of draggable layers on content and hides the alerts on the canvas.
> chore: add gamesource to drag list, hide alert on canvas

- package-lock.json
- package.json
- src/core/index.ts
- src/core/types.ts
This PR integrates three new endpoints from api.stream: getGuestCodes, createGuestCode, and deleteGuestCode. These endpoints allow us to manage guest links for users effectively.
> chore: add support for new guest-link apis

- package-lock.json
- package.json
- src/core/webrtc/simple-room.ts
The selected device ID for adding the camera should be enforced, regardless of whether it meets the resolution constraints.
https://xsolla.atlassian.net/browse/LSTREAM-741
> chore: enforce the selected deviceId

- package-lock.json
- package.json
- src/core/webrtc/simple-room.ts
The selected device ID for adding the camera should be enforced, regardless of whether it meets the resolution constraints.
https://xsolla.atlassian.net/browse/LSTREAM-741
> chore: enforce camera selection

- package-lock.json
- package.json
- src/core/transforms/GameSource.tsx
- src/helpers/sceneless-project.ts
- This check will prevent errors when a project is removed, and someone still attempts to access its props after a Studio account deletion.
- Also, it reverts the code where we set the opacity of the AlertContainer to zero when VideoOverlay is enabled.
https://xsolla.atlassian.net/browse/LSTREAM-775
> fix: minor bug fixes

- package-lock.json
- package.json
- src/core/transforms/components/Iframe.tsx
- src/core/types.ts
- src/helpers/sceneless-project.ts
This update introduces support for enabling multiple custom overlays within the platform. Users can now activate more than one overlay simultaneously.
**Note:** This update currently targets custom overlays only. In the future, we plan to extend this functionality to include image overlays as well
https://xsolla.atlassian.net/browse/LSTREAM-796
> feat: add support for enabling multiple custom overlays

- package-lock.json
- package.json
- src/core/layouts/index.ts
- src/helpers/compositor.tsx
- src/helpers/database.ts
- src/helpers/sceneless-project.ts
When a new node is added to the canvas, the useEffect hook for the previous node is triggered twice—once for the previous node and once for the new node. This causes the previous node to be removed and then re-added to the canvas, creating a flickering effect.
Previously, this issue didn’t occur because the canvas only supported a single child node at any given time. However, with the recent requirement to support multiple overlays within the same container, this behavior has surfaced as a problem.
From a technical perspective, I believe adding refs to the dependency array of the useEffect is unnecessary since refs are generally stable across React render cycles.
https://github.com/user-attachments/assets/a40f2857-f1fc-4d0c-8b35-772252897dfb
https://xsolla.atlassian.net/browse/LSTREAM-811
> feat: effects called multiple time when adding new element for first ime

- package.json
- src/compositor/html/html-layouts.tsx
- src/helpers/compositor.tsx
- src/helpers/sceneless-project.ts
This PR addresses two issues observed in OpenTail related to the GameSource component:
**Flickering When Adding a New Participant**
- 	The flickering occurred because the layout calculation for GameSource sets the inset property to auto during load time.
- 	When inset is auto, it positions the element dynamically based on its containing block. This behavior causes reflows and repaints during layout updates, leading to flickering.
- 	Fix: Updated the logic to use fixed px values for inset instead of relying on auto. This ensures stable positioning and avoids recalculation during reflows.
**Gaps Around the GameSource Component**
- 	The gaps were a side effect of the pre-optimization attempt using the will-change property.
- 	According to the [MDN …
> fix: gamesource gap

- .gitignore
- package-lock.json
- package.json
- src/core/data.ts
- src/core/index.ts
- src/core/requests.ts
- src/core/types.ts
Added a new option/flag to the studio.load function to conditionally trigger layout updates. 
The video rendering resolution and canvas resolution are two distinct things. For canvas resolution, we strictly support 720p and 1080p, depending on the user’s plan. However, the video rendering resolution can go as low as 480p if required.
When the user modifies the video rendering resolution and reloads the project, the initial `studio.load` resets the video rendering resolution to match the canvas resolution. This reset is based on the user’s plan, which determines whether the canvas resolution is set to 720p or 1080p.
https://xsolla.atlassian.net/browse/LSTREAM-805
> chore: Add Option to Update Layout Only for Resolution Change in Studio Load Function

- package-lock.json
- package.json
- src/core/transforms/Alert.tsx
- src/core/transforms/Overlay.tsx
Add 'allow' attribute to iframe to enable audio autoplay
It appears that Chrome or an iframe policy update now requires this attribute for autoplay. Previously, it wasn't needed,
but adding it now ensures audio will play as expected.
https://xsolla.atlassian.net/browse/LSTREAM-963
> feat: add autoplay attribute to Alert and Overlay components
